name: Push Coder Template

on:
  push:
    tags:
      - "v*"

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Coder CLI
        run: |
          curl -fsSL https://coder.com/install.sh | sh

      - name: Log in to Coder
        run: coder login --token ${{ secrets.CODER_TOKEN }} --url https://embold.dev --no-version-warning

      - name: Push PHP Template
        run: yes | coder template push php
